[package]
name = "web_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
reqwest = "0.12.24"
scraper = "0.24.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
